### PR TITLE
[WIP] Ember 1.13 compatibility

### LINKED ISSUE #43: [EMBERJS] Object proxying is depreciated
After upgrading ember-cli to 0.2.2 I'm seeing many depreciation notices in my console:

I'm currently running 0.0.19 of ember-google-map, the only difference I see between 0.0.20 is "[Always auto-fit bounds feature](https://github.com/huafu/ember-google-map/commit/21651adf8f38573948dc11fb9d907af39efab5dd)" So I don't think upgrading will fix it.

    DEPRECATION: You attempted to set `lat` from `<app@controller:google-map/marker::ember541>`, but object proxying is deprecated. Please use `model.lat` instead. See http://emberjs.com/guides/deprecations/#toc_objectcontroller for more details.
        at exports.default.mixin.Mixin.create.setUnknownProperty

I'm seeing the depreciation for the following properties:

- lat
- lng
- isWindowVisible
- zIndex
- googleEvents
- isVisible
- isClickable
- icon
- opacity
- title
- isDraggable
- infoWindowTemplateName
- templateName
- hasInfoWindow

I can provide any additional info needed.
Thanks!

### PR DESCRIPTION
**Pull request by huafu**
This will fix #43 and #67.

- [x] update `ember-cli` to latest version
- [x] change all computed properties to follow the new declaration syntax
- [x] remove any use of `Ember.ObjectController`
- [x] remove all remaining usage of extended prototypes
- [x] fix the marker info-windows (some aliasing is wrong somewhere)
- [x] update from Ember `1.12` to `1.13`
- [x] check and fix everything again ;-)

### CODE REVIEW

**Comment by lukemcfarlane** [comment]
I noticed that the ember version specified in `bower.json` is `1.12.0`. Is this deliberate, or should this be 1.13.0?

**Comment by lukemcfarlane** [comment]
I have opened a PR to fix the info windows:
https://github.com/huafu/ember-google-map/pull/70

**Comment by lukemcfarlane** [comment]
RE my prior comment, would it be worth just renaming this PR to "[WIP] Ember 1.12 compatibility" and then opening a new one for 1.13?

I have tried upgrading ember to 1.13 and installing the ember-legacy-views addon, however things are still looking fairly broken. It might be a bit of work.

**Comment by huafu** [comment]
Thanks @lukemcfarlance!
No the `1.12` isn't what it should be, I guess it's because I just updated `ember-cli` and ran `ember init` expectin it to update the ember version to `1.13`... Let's hope there's not too much breaking changes between those two ;-)

**Comment by lukemcfarlane** [comment]
Something weird is happening at `app/views/google-map/polyline.js:52` that is preventing polylines/polygons from showing after upgrading to Ember 1.13. `this.get('controller')` seems to be returning the google-map component as opposed to the polygon controller, from which it is hence unable to get the `_path`.

**Comment by huafu** [comment]
@lukemcfarlane yeah I guess that is why it needs a big refactor instead of this dirty quick update. I believe all views there should be changed to components so that this can be possible instead of setting all properties of the component:
```hbs
{{#google-maps}}
  {{google-maps-marker lat=something.lat lng=something.lng ...}}
  {{google-maps-polyline path=somethingElse.path ...}}
  ...
{{/google-maps}}
```

**Comment by lukemcfarlane** [comment]
@huafu Yes I agree, would you be happy to draw the line at 1.12 then for this "dirty quick update"?

**Comment by huafu** [comment]
Not sure what you call `drawing the line` (English isn't my native lang), but I have update to `1.13` in my local and I'm going to fix the little issues you're referring to, merge, publish, and then I can start on the refactor. But I do not have much free time lately.... that is why I wanted that "dirty" but quick fix first

**Comment by lukemcfarlane** [comment]
https://github.com/huafu/ember-google-map/pull/71

**Comment by huafu** [comment]
Now I can't figure out why I have some handlebars template errors:
```
File: dummy/templates/components/google-map.hbs
Parse error on line 17:
...s=polylineViewClass as |polyline|}}  </
-----------------------^
Expecting 'CLOSE', got 'OPEN_BLOCK_PARAMS'
```

**Comment by lukemcfarlane** [comment]
@huafu this PR fixes the build error:
https://github.com/huafu/ember-google-map/pull/72

**Comment by huafu** [comment]
Thanks @lukemcfarlane, so that means we can't have non block `each` in Glimmer :-/

**Comment by Matt-Jensen** [comment]
I'm Interested in contributing.  Obviously debugging Markers ect. is needed.  Is converting Views to Components part of this release?

**Comment by Matt-Jensen** [comment]
This may be a naive approach: 
https://github.com/Matt-Jensen/ember-google-map/tree/feature/ember-1-13-compatibility
(Markers are now rendering, with some bugs)

However wouldn't we able to simplify the code base by referencing the component model directly in its' template and avoid use of controllers altogether?  Of course we'll need a new way to customize template names ect.

**Comment by huafu** [comment]
@Matt-Jensen the goal of this release is simply to make it work as expected with Ember `1.13`. A big refactor is going on in parallel, but here we just need to make it work like it is with no refactor with `1.13`. You're more than welcome to help. I'm going to look at your branch.

**Comment by huafu** [comment]
So @Matt-Jensen we can't take your approach since it's not handling all what the previous version was handling. What is not working with markers?

**Comment by Matt-Jensen** [comment]
FYI ember-cli seems to have updated to 1.13.1, happy to make a PR.

**Comment by huafu** [comment]
Thanks @Matt-Jensen, tho I've fixed the latest bugs and I need to make a release now. When I will have more free time I'll continue my clean refactor ;-)

**Comment by Matt-Jensen** [comment]
There is an issue with this branch: the ev_ events are not functioning.  May need to do a quick revert.

**Comment by huafu** [comment]
No quick revert, but I think I know why. They need to be aliased as well :-/
The big thing needed is to finish the refactor, tho I got no time lately....

**Pull request merged**
